mappings:
  ProductQuestion_ProductVariationDecorator: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductVariationDecorator
  ProductQuestion_OrderExtension: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_OrderExtension
  ProductQuestion: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion
  ProductQuestion_ProductDecorator: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductDecorator
  ProductQuestion_ProductControllerDecorator: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductControllerDecorator
  ProductQuestion_ProductAttributeValues: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductAttributeValues
  ProductQuestion_ProductAttributeTypes: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductAttributeTypes
  ProductQuestion_ProductVariationsAdditions: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductVariationsAdditions
  ProductQuestion_OrderItemExtension: Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_OrderItemExtension
  ProductQuestionImageSelectorField: Sunnysideup\EcommerceProductQuestions\Form\ProductQuestionImageSelectorField
