---
Name: ProductQuestionMain
---
Sunnysideup\Ecommerce\Pages\Product:
  extensions:
    - Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductDecorator
Sunnysideup\Ecommerce\Pages\ProductController:
  extensions:
    - Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductControllerDecorator
Sunnysideup\Ecommerce\Model\Order:
  extensions:
    - Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_OrderExtension
Sunnysideup\Ecommerce\Model\OrderItem:
  extensions:
    - Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_OrderItemExtension
Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion:
  number_per_row: 1
Sunnysideup\Ecommerce\Cms\ProductConfigModelAdmin:
  managed_models:
    - Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion
---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - Sunnysideup\EcommerceProductQuestions\Model\ProductQuestion_ProductVariationDecorator
